import { Chapter } from './types';

export const SYLLABUS: Chapter[] = [
  // Physics
  { id: 'p1', name: 'Units and Measurements', subject: 'Physics', category: 'General' },
  { id: 'p2', name: 'Kinematics', subject: 'Physics', category: 'Mechanics' },
  { id: 'p3', name: 'Laws of Motion', subject: 'Physics', category: 'Mechanics' },
  { id: 'p4', name: 'Work, Energy and Power', subject: 'Physics', category: 'Mechanics' },
  { id: 'p5', name: 'Rotational Motion', subject: 'Physics', category: 'Mechanics' },
  { id: 'p6', name: 'Gravitation', subject: 'Physics', category: 'Mechanics' },
  { id: 'p7', name: 'Properties of Solids and Liquids', subject: 'Physics', category: 'Properties of Matter' },
  { id: 'p8', name: 'Thermodynamics', subject: 'Physics', category: 'Heat' },
  { id: 'p9', name: 'Kinetic Theory of Gases', subject: 'Physics', category: 'Heat' },
  { id: 'p10', name: 'Oscillations and Waves', subject: 'Physics', category: 'Waves' },
  { id: 'p11', name: 'Electrostatics', subject: 'Physics', category: 'Electricity' },
  { id: 'p12', name: 'Current Electricity', subject: 'Physics', category: 'Electricity' },
  { id: 'p13', name: 'Magnetic Effects of Current and Magnetism', subject: 'Physics', category: 'Magnetism' },
  { id: 'p14', name: 'Electromagnetic Induction and AC', subject: 'Physics', category: 'Magnetism' },
  { id: 'p15', name: 'Electromagnetic Waves', subject: 'Physics', category: 'Optics' },
  { id: 'p16', name: 'Optics', subject: 'Physics', category: 'Optics' },
  { id: 'p17', name: 'Dual Nature of Matter and Radiation', subject: 'Physics', category: 'Modern Physics' },
  { id: 'p18', name: 'Atoms and Nuclei', subject: 'Physics', category: 'Modern Physics' },
  { id: 'p19', name: 'Electronic Devices', subject: 'Physics', category: 'Modern Physics' },

  // Chemistry
  { id: 'c1', name: 'Some Basic Concepts in Chemistry', subject: 'Chemistry', category: 'Physical' },
  { id: 'c2', name: 'States of Matter', subject: 'Chemistry', category: 'Physical' },
  { id: 'c3', name: 'Atomic Structure', subject: 'Chemistry', category: 'Physical' },
  { id: 'c4', name: 'Chemical Bonding and Molecular Structure', subject: 'Chemistry', category: 'Physical' },
  { id: 'c5', name: 'Chemical Thermodynamics', subject: 'Chemistry', category: 'Physical' },
  { id: 'c6', name: 'Solutions', subject: 'Chemistry', category: 'Physical' },
  { id: 'c7', name: 'Equilibrium', subject: 'Chemistry', category: 'Physical' },
  { id: 'c8', name: 'Redox Reactions and Electrochemistry', subject: 'Chemistry', category: 'Physical' },
  { id: 'c9', name: 'Chemical Kinetics', subject: 'Chemistry', category: 'Physical' },
  { id: 'c10', name: 'Surface Chemistry', subject: 'Chemistry', category: 'Physical' },
  { id: 'c11', name: 'Classification of Elements and Periodicity', subject: 'Chemistry', category: 'Inorganic' },
  { id: 'c12', name: 'General Principles and Processes of Isolation of Metals', subject: 'Chemistry', category: 'Inorganic' },
  { id: 'c13', name: 'Hydrogen', subject: 'Chemistry', category: 'Inorganic' },
  { id: 'c14', name: 'S-Block Elements', subject: 'Chemistry', category: 'Inorganic' },
  { id: 'c15', name: 'P-Block Elements', subject: 'Chemistry', category: 'Inorganic' },
  { id: 'c16', name: 'D and F Block Elements', subject: 'Chemistry', category: 'Inorganic' },
  { id: 'c17', name: 'Coordination Compounds', subject: 'Chemistry', category: 'Inorganic' },
  { id: 'c18', name: 'Environmental Chemistry', subject: 'Chemistry', category: 'Inorganic' },
  { id: 'c19', name: 'Purification and Characterization of Organic Compounds', subject: 'Chemistry', category: 'Organic' },
  { id: 'c20', name: 'Some Basic Principles of Organic Chemistry', subject: 'Chemistry', category: 'Organic' },
  { id: 'c21', name: 'Hydrocarbons', subject: 'Chemistry', category: 'Organic' },
  { id: 'c22', name: 'Organic Compounds Containing Halogens', subject: 'Chemistry', category: 'Organic' },
  { id: 'c23', name: 'Organic Compounds Containing Oxygen', subject: 'Chemistry', category: 'Organic' },
  { id: 'c24', name: 'Organic Compounds Containing Nitrogen', subject: 'Chemistry', category: 'Organic' },
  { id: 'c25', name: 'Polymers', subject: 'Chemistry', category: 'Organic' },
  { id: 'c26', name: 'Biomolecules', subject: 'Chemistry', category: 'Organic' },
  { id: 'c27', name: 'Chemistry in Everyday Life', subject: 'Chemistry', category: 'Organic' },

  // Mathematics
  { id: 'm1', name: 'Sets, Relations and Functions', subject: 'Mathematics', category: 'Algebra' },
  { id: 'm2', name: 'Complex Numbers and Quadratic Equations', subject: 'Mathematics', category: 'Algebra' },
  { id: 'm3', name: 'Matrices and Determinants', subject: 'Mathematics', category: 'Algebra' },
  { id: 'm4', name: 'Permutations and Combinations', subject: 'Mathematics', category: 'Algebra' },
  { id: 'm5', name: 'Mathematical Induction', subject: 'Mathematics', category: 'Algebra' },
  { id: 'm6', name: 'Binomial Theorem and its Simple Applications', subject: 'Mathematics', category: 'Algebra' },
  { id: 'm7', name: 'Sequences and Series', subject: 'Mathematics', category: 'Algebra' },
  { id: 'm8', name: 'Limit, Continuity and Differentiability', subject: 'Mathematics', category: 'Calculus' },
  { id: 'm9', name: 'Integral Calculus', subject: 'Mathematics', category: 'Calculus' },
  { id: 'm10', name: 'Differential Equations', subject: 'Mathematics', category: 'Calculus' },
  { id: 'm11', name: 'Coordinate Geometry', subject: 'Mathematics', category: 'Geometry' },
  { id: 'm12', name: 'Three Dimensional Geometry', subject: 'Mathematics', category: 'Geometry' },
  { id: 'm13', name: 'Vector Algebra', subject: 'Mathematics', category: 'Algebra' },
  { id: 'm14', name: 'Statistics and Probability', subject: 'Mathematics', category: 'Statistics' },
  { id: 'm15', name: 'Trigonometry', subject: 'Mathematics', category: 'Trigonometry' },
  { id: 'm16', name: 'Mathematical Reasoning', subject: 'Mathematics', category: 'Algebra' },
];
